{{- if .Values.ingress.redirects -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pet2cattle.fullname" . }}-redirector
  labels:
    {{- include "pet2cattle.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.redirector.replicaCount }}
{{- end }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      {{- include "pet2cattle.selectorLabels" . | nindent 6 }}
      component: redirector
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "pet2cattle.selectorLabels" . | nindent 8 }}
        component: redirector
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}  
      containers:
        - name: {{ .Chart.Name }}
          command:
          - "/usr/local/bin/gunicorn"
          - "app:app"
          - "--bind"
          - "0.0.0.0:8000"
          - "--keep-alive"
          - "1"
          - "--chdir"
          - "redirector"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIRECT
              {{- with (index .Values.ingress.hosts 0) }}
              value: {{ . }}
              {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP         
          startupProbe:
            httpGet:
              path: /liveness
              port: http
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
          readinessProbe:
            httpGet:
              path: /liveness
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
