apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pet2cattle.fullname" . }}-static
  labels:
    {{- include "pet2cattle.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.static.replicaCount }}
  selector:
    matchLabels:
      {{- include "pet2cattle.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "pet2cattle.selectorLabels" . | nindent 8 }}
        component: static
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: git-repo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [ "sh", "-xc", "git clone {{ .Values.pet2cattle.posts.repo }} /media/usb" ]
        {{- if .Values.s3sync.key }}
        env:
          - name: GIT_SSH_COMMAND
            value: "ssh -vvv -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /root/deploykeys/id_rsa"
        {{- end }}
        volumeMounts:
          - mountPath: /media/usb
            name: static-data
          {{- if .Values.s3sync.key }}
          - name: deploykeys
            mountPath: /root/deploykeys
          {{- end }}
      containers:
      - name: pet2cattle-static
        image: "{{ .Values.static.repository }}:{{ .Values.static.tag | default "alpine" }}"
        resources:
          requests:
            memory: "50Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
          - name: http
            containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: static-data
            subPath: static
        startupProbe:
          httpGet:
            path: /health
            port: http
        livenessProbe:
          httpGet:
            path: /health
            port: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
      volumes:
        - name: static-data
          emptyDir: {}
        {{- if .Values.s3sync.key }}
        - name: deploykeys
          secret:
            defaultMode: 0600
            secretName: {{ .Release.Name }}-deploykeys
        {{- end }}