{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.tls -}}
{{- $fullName := include "pet2cattle.fullname" . -}}
{{- $shortName := include "pet2cattle.name" . -}}
{{- $appPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-https
  labels:
    {{- include "pet2cattle.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls.hosts }}
  tls:
    - hosts:
        {{- with (first .Values.ingress.tls.hosts) }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ $shortName }}-cert-https
  {{- end }}
  rules:
    {{- with (first .Values.ingress.hosts) }}
    # - host: {{ . | quote }}
    #   http:
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: {{ $fullName }}
    #             port:
    #               name: http
    - host: "static.{{ . }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-static
                port:
                  name: http
    {{- end }}
  {{- end }}
  {{- end }}